name: Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-docs:
    strategy:
      fail-fast: true
      matrix:
        config:
          - preset: linux-x64
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install System Packages
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake ninja-build python3 python3-pip doxygen
          sudo pip3 install gcovr
          sudo pip3 install -r docs/requirements.txt

      - name: Setup vcpkg
        working-directory: /opt
        run: |
          rm -rf vcpkg
          git clone --single-branch https://github.com/Microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh
          ./vcpkg/vcpkg integrate install
          ./vcpkg/vcpkg --version
          test -d vcpkg-binary-cache || mkdir vcpkg-binary-cache

      - name: Cache Vcpkg Dependencies
        uses: actions/cache@v4
        with:
          key: ${{matrix.config.preset}}-${{hashFiles('vcpkg.json')}}
          path: /opt/vcpkg-binary-cache

      - name: Configure
        env:
          VCPKG_ROOT: /opt/vcpkg
          VCPKG_DEFAULT_BINARY_CACHE: /opt/vcpkg-binary-cache
        run: cmake -S . --preset ${{matrix.config.preset}} -DPARSI_ENABLE_COVERAGE=ON -DPARSI_BENCHMARK=ON -DPARSI_DOCS=ON

      - name: Build Debug
        run: |
          cmake --build --preset ${{matrix.config.preset}} --config Debug

      - name: Build Release
        run: |
          cmake --build --preset ${{matrix.config.preset}} --config Release

      - name: Test
        run: |
          ctest -C Debug --preset linux-tests

      - name: Generate Coverage
        run: |
          cmake --build --preset ${{matrix.config.preset}} --config Debug --target coverage

      - name: Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: build/${{matrix.config.preset}}/coverage/coverage.xml
          fail_ci_if_error: true
          functionalities: fix

      - name: Build Docs
        if: false
        run: |
          cmake --build --preset ${{matrix.config.preset}} --target docs

      - name: Upload Pages Artifacts
        if: false
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/${{matrix.config.preset}}/docs/sphinx/

  deploy-docs:
    if: false && success() && github.ref == 'refs/heads/main'
    needs: build-test-docs
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
